// generated by prs from index.tsx + HoffResearchCard.module.sass; do not edit
use plev::builder::{Element, div, text};
use plev::theme::Theme;

pub fn hoff_research_card(children: Element, title: &str, content: &str) -> Element {
    let theme = Theme::hoff();
    div()
        .w(368.0)
        .clip_children()
        .bg(plev::theme::hoff::CARD_OVERLAY)
        .backdrop_blur(theme.effects.blur_sigma)
        .shadow_inset(16.0, [2.0, 4.0], theme.glass.inset_highlight)
        .rounded(theme.radius.xl)
        .border(1.5)
        .border_color(theme.glass.edge_soft)
        .child(
            div()
                .pt(16.0)
                .px(16.0)
                .pb(32.0)
                .child(
                    div()
                        .h(336.0)
                        .child(children)
                )
                .child(
                    div()
                        .h(16.0)
                )
                .child(
                    div()
                        .px(16.0)
                        .child(
                            text(title)
                                .font_size(20.0)
                                .line_height(24.0)
                                .font_weight(500)
                                .text_color(theme.colors.text)
                        )
                        .child(
                            div()
                                .h(8.0)
                        )
                        .child(
                            text(content)
                                .font_size(16.0)
                                .line_height(24.0)
                                .text_color(theme.colors.text_mid)
                        )
                        .child(
                            div()
                                .h(24.0)
                        )
                        .child(
                            div()
                                .py(12.0)
                                .px(32.0)
                                .clip_children()
                                .rounded(theme.radius.xl)
                                .bg(theme.glass.button)
                                .shadow_inset(16.0, [2.0, 4.0], theme.glass.inset_highlight)
                                .backdrop_blur(theme.effects.blur_sigma)
                                .border(1.0)
                                .border_color(plev::theme::hoff::n2(0.25))
                                .child(
                                    text("Discover")
                                        .font_size(16.0)
                                        .line_height(24.0)
                                        .font_weight(500)
                                        .text_color(theme.colors.text_mid)
                                )
                        )
                )
        )
}
