// generated by prs from separator.rs (Separator::horizontal().label(..)); do not edit
use plev::builder::{Element, Justify, div, text};
use plev::theme::Theme;

pub fn separator(label: &str) -> Element {
    let theme = Theme::hoff();
    div()
        .row()
        .shrink(0.0)
        .align_center()
        .justify(Justify::Center)
        .child(
            div()
                .h(1.0)
                .grow(1.0)
                .bg(theme.colors.divider)
        )
        .child(
            div()
                .px(8.0)
                .py(4.0)
                .bg(theme.colors.bg)
                .child(
                    text(label)
                        .font_size(12.0)
                        .line_height(16.0)
                        .text_color(theme.colors.text_mid)
                )
        )
        .child(
            div()
                .h(1.0)
                .grow(1.0)
                .bg(theme.colors.divider)
        )
}
