return {
    descricao = [[
        camada 3 — primitivos headless: comportamento sem visual (acessibilidade,
        teclado, foco, aria, estados; zero estilo). varios usam state machines
        internamente (zag.js explicitamente, base de ark ui). dados 2025/2026.
    ]],
    itens = {
        {
            nome = "ariakit",
            github = "https://github.com/ariakit/ariakit",
            docs = "https://ariakit.org/",
            stars = 8600,
            forks = 411,
            ano = 2017,
            framework_alvo = [[react]],
            usa_state_machine = false,
            features = [[primitivos unstyled + exemplos estilizados copy-paste,
                wai-aria, foco em padroes modernos de react, dx]],
            componentes = "40+ patterns",
            pros = [[acessivel, exemplos estilizados, react moderno]],
            contras = [[so react, comunidade menor que radix]],
            licenca = "mit",
            empresa = "diego haz (oss)",
            estado = "ativo",
        },
        {
            nome = "ark_ui",
            github = "https://github.com/chakra-ui/ark",
            docs = "https://ark-ui.com/",
            stars = 5200,
            forks = 200,
            ano = 2023,
            framework_alvo = [[react, vue, solid, svelte (multi-framework)]],
            usa_state_machine = true,
            features = [[construido sobre zag.js (state machines finitas), 45+
                componentes, wai-aria testado com leitores de tela, api identica
                cross-framework, unstyled]],
            componentes = "45+",
            pros = [[multi-framework, state machines, acessibilidade rigorosa,
                base de chakra/park ui]],
            contras = [[mais novo, menos exemplos estilizados que radix]],
            licenca = "mit",
            empresa = "chakra systems",
            estado = "ativo",
        },
        {
            nome = "base_ui",
            github = "https://github.com/mui/base-ui",
            docs = "https://base-ui.com/",
            stars = 9800,
            forks = 448,
            ano = 2024,
            framework_alvo = [[react]],
            usa_state_machine = false,
            features = [[unstyled, low-level hooks + componentes, controle total de
                css/acessibilidade; "material ui sem o material design"; criado pelo
                time do mui + radix]],
            componentes = "crescendo (30+)",
            pros = [[mantido ativamente (substitui radix como camada primitiva mais
                ativa), backing mui, acessivel]],
            contras = [[novo, so react, ainda em evolucao]],
            licenca = "mit",
            empresa = "mui + ex-radix",
            estado = "ativo",
        },
        {
            nome = "bits_ui",
            github = "https://github.com/huntabyte/bits-ui",
            docs = "https://bits-ui.com/",
            stars = 1500,
            forks = 130,
            ano = 2023,
            framework_alvo = [[svelte]],
            usa_state_machine = false,
            features = [[primitivos headless para svelte, acessivel, base do
                shadcn-svelte]],
            componentes = "40+",
            pros = [[svelte-native, base do shadcn-svelte, acessivel]],
            contras = [[so svelte, comunidade menor]],
            licenca = "mit",
            empresa = "huntabyte (oss)",
            estado = "ativo",
        },
        {
            nome = "corvu",
            github = "https://github.com/corvudev/corvu",
            docs = "https://corvu.dev/",
            stars = 600,
            forks = 30,
            ano = 2024,
            framework_alvo = [[solid]],
            usa_state_machine = false,
            features = [[primitivos unstyled e acessiveis para solidjs]],
            componentes = "15+",
            pros = [[solid-native, acessivel]],
            contras = [[so solid, muito novo, comunidade pequena]],
            licenca = "mit",
            empresa = "jasmin moeller (oss)",
            estado = "ativo",
        },
        {
            nome = "downshift",
            github = "https://github.com/downshift-js/downshift",
            docs = "https://www.downshift-js.com/",
            stars = 12000,
            forks = 900,
            ano = 2017,
            framework_alvo = [[react]],
            usa_state_machine = true,
            features = [[primitivo wai-aria para inputs avancados (autocomplete,
                combobox, select), state reducer pattern]],
            componentes = "inputs/combobox/select",
            pros = [[maduro, acessivel, padrao para autocomplete]],
            contras = [[escopo limitado (inputs), so react]],
            licenca = "mit",
            empresa = "kent c. dodds (oss)",
            estado = "ativo",
        },
        {
            nome = "floating_ui",
            github = "https://github.com/floating-ui/floating-ui",
            docs = "https://floating-ui.com/",
            stars = 32600,
            forks = 1700,
            ano = 2019,
            framework_alvo = [[agnostico (react, vue, etc); core js puro]],
            usa_state_machine = false,
            features = [[posicionamento de elementos flutuantes (tooltips, popovers,
                dropdowns), middleware (flip/shift/offset), sucessor do popper.js]],
            componentes = "posicionamento (nao componentes)",
            pros = [[padrao de fato para posicionamento, agnostico, leve]],
            contras = [[so posicionamento (nao um kit completo)]],
            licenca = "mit",
            empresa = "atomiks (oss)",
            estado = "ativo",
        },
        {
            nome = "headless_ui",
            github = "https://github.com/tailwindlabs/headlessui",
            docs = "https://headlessui.com/",
            stars = 28600,
            forks = 1200,
            ano = 2020,
            framework_alvo = [[react, vue]],
            usa_state_machine = false,
            features = [[~10 componentes unstyled, integra com tailwind, api
                beginner-friendly, acessivel]],
            componentes = "~10",
            pros = [[integra perfeito com tailwind, simples, do time tailwind]],
            contras = [[poucos componentes, sem combobox-com-virtualizacao avancado]],
            licenca = "mit",
            empresa = "tailwind labs",
            estado = "ativo",
        },
        {
            nome = "kobalte",
            github = "https://github.com/kobaltedev/kobalte",
            docs = "https://kobalte.dev/",
            stars = 1788,
            forks = 110,
            ano = 2023,
            framework_alvo = [[solid]],
            usa_state_machine = false,
            features = [[primitivos acessiveis e unstyled para solidjs, wai-aria]],
            componentes = "30+",
            pros = [[solid-native, acessivel, completo para solid]],
            contras = [[so solid, comunidade menor]],
            licenca = "mit",
            empresa = "kobalte (oss)",
            estado = "ativo",
        },
        {
            nome = "melt_ui",
            github = "https://github.com/melt-ui/melt-ui",
            docs = "https://melt-ui.com/",
            stars = 4200,
            forks = 228,
            ano = 2023,
            framework_alvo = [[svelte]],
            usa_state_machine = false,
            features = [[builders headless e acessiveis para svelte, controle total
                de markup/estilo]],
            componentes = "40+ builders",
            pros = [[svelte-native, builders flexiveis, acessivel]],
            contras = [[so svelte]],
            licenca = "mit",
            empresa = "melt ui (oss)",
            estado = "ativo",
        },
        {
            nome = "radix_ui",
            github = "https://github.com/radix-ui/primitives",
            docs = "https://www.radix-ui.com/primitives",
            stars = 19000,
            forks = 1200,
            ano = 2020,
            framework_alvo = [[react]],
            usa_state_machine = false,
            features = [[30+ primitivos unstyled acessiveis (dialog, dropdown, tabs,
                popover), keyboard nav, foco, aria, rtl, asChild (composicao); base
                do shadcn/ui; @radix-ui/react-slot ~131m downloads/semana]],
            componentes = "30+",
            pros = [[popularizou headless em react, base de shadcn, acessivel,
                composicao asChild]],
            contras = [[adquirido pela workos, velocidade de updates desacelerou em
                alguns componentes (combobox/multi-select), so react]],
            licenca = "mit",
            empresa = "workos (ex-radix)",
            estado = "ativo (lento)",
        },
        {
            nome = "react_aria",
            github = "https://github.com/adobe/react-spectrum",
            docs = "https://react-spectrum.adobe.com/react-aria/",
            stars = 15300,
            forks = 1400,
            ano = 2019,
            framework_alvo = [[react]],
            usa_state_machine = false,
            features = [[biblioteca de hooks (useButton, useDialog) + componentes,
                aria semantics, i18n (rtl, locale-aware), 40+ patterns; a opcao mais
                rigorosa em acessibilidade; parte do react spectrum]],
            componentes = "40+ patterns",
            pros = [[acessibilidade/i18n mais rigorosa, hooks granulares, backing
                adobe]],
            contras = [[hooks-first verboso (mais codigo por componente), so react]],
            licenca = "apache-2.0",
            empresa = "adobe",
            estado = "ativo",
        },
        {
            nome = "reka_ui",
            github = "https://github.com/unovue/reka-ui",
            docs = "https://reka-ui.com/",
            stars = 5000,
            forks = 300,
            ano = 2021,
            framework_alvo = [[vue]],
            usa_state_machine = false,
            features = [[primitivos headless e acessiveis para vue (ex radix vue,
                rebrand 2025), unstyled, base de nuxt ui/shadcn-vue]],
            componentes = "30+",
            pros = [[radix para vue, acessivel, base de shadcn-vue/nuxt ui]],
            contras = [[so vue]],
            licenca = "mit",
            empresa = "unovue (oss)",
            estado = "ativo",
        },
        {
            nome = "tanstack",
            github = "https://github.com/TanStack",
            docs = "https://tanstack.com/",
            stars = 0,
            forks = 0,
            ano = 2019,
            framework_alvo = [[react, vue, solid, svelte (multi-framework)]],
            usa_state_machine = false,
            features = [[headless: table (datagrids), virtual (virtualizacao de
                listas), query (state assincrono), form, router; sem markup/estilos;
                100% typescript]],
            componentes = "table/virtual/query/form/router",
            pros = [[headless puro, multi-framework, type-safe, controle total de
                markup, parceria com ag grid]],
            contras = [[so logica (sem componentes visuais), curva de aprendizado]],
            licenca = "mit",
            empresa = "tanner linsley / tanstack",
            estado = "ativo",
        },
        {
            nome = "zag_js",
            github = "https://github.com/chakra-ui/zag",
            docs = "https://zagjs.com/",
            stars = 5085,
            forks = 255,
            ano = 2021,
            framework_alvo = [[react, vue, solid, svelte (agnostico)]],
            usa_state_machine = true,
            features = [[MAQUINAS DE ESTADO FINITAS explicitas (statecharts) para
                logica de componentes; adapters react/vue/solid/svelte; acessibilidade
                (teclado/foco/aria), unstyled,  e2e por wai-aria; base de ark ui e
                chakra ui]],
            componentes = "dialog/tooltip/menu/number-input/etc (state machines)",
            pros = [[state machines = logica testavel/previsivel, write-once
                use-everywhere, acessivel, framework-agnostic]],
            contras = [[mais low-level (precisa de wrapper como ark para uso rapido)]],
            licenca = "mit",
            empresa = "chakra systems (segun adebayo)",
            estado = "ativo",
        },
    },
}
