return {
    descricao = [[
        camada 4 — bibliotecas de componentes / design systems: "a roupa".
        sub-distincao: tipo="design_system" = especificacao visual/comportamento
        (material, hig, fluent, carbon, polaris); tipo="biblioteca" = implementacao
        em codigo. dados 2025/2026.
    ]],
    itens = {
        {
            nome = "ant_design",
            tipo = "biblioteca",
            github = "https://github.com/ant-design/ant-design",
            docs = "https://ant.design/",
            stars = 94000,
            forks = 51000,
            ano = 2015,
            framework = [[react (typescript)]],
            base = [[primitivos proprios]],
            features = [[60+ componentes enterprise (table, form, tree, transfer,
                cascader), i18n 50+ locales, rtl, ant design pro (protable/proform/
                prolayout); v6 nov/2025 com +40% perf de render no dev]],
            pros = [[componentes enterprise mais ricos, tudo gratis (mit), i18n
                built-in, design consistente]],
            contras = [[arvore de dependencias pesada (48 deps diretas), docs
                chinese-first as vezes, customizacao limitada]],
            licenca = "mit",
            empresa = "ant group (alibaba)",
            estado = "ativo",
        },
        {
            nome = "apple_hig",
            tipo = "design_system",
            github = "n/a (spec)",
            docs = "https://developer.apple.com/design/human-interface-guidelines/",
            stars = 0,
            forks = 0,
            ano = 1987,
            framework = [[spec; implementada por swiftui/uikit/cupertino]],
            base = [[especificacao]],
            features = [[guidelines de layout, navegacao, fontes, cores, movimento;
                por plataforma (ios/macos/watchos/tvos/visionos); clareza, deferencia,
                profundidade]],
            pros = [[gold standard ios/macos, experiencia nativa, consistencia
                cross-device apple]],
            contras = [[ecossistema fechado apple, regras rigidas, menos flexivel]],
            licenca = "proprietaria (guidelines)",
            empresa = "apple",
            estado = "ativo",
        },
        {
            nome = "atlassian_design_system",
            tipo = "design_system",
            github = "https://github.com/atlassian/design-system",
            docs = "https://atlassian.design/",
            stars = 1000,
            forks = 200,
            ano = 2017,
            framework = [[react (implementacao)]],
            base = [[especificacao + componentes]],
            features = [[tokens, cor, iconografia, tipografia, conteudo, brand;
                powering jira/confluence/trello; foco em ferramentas enterprise]],
            pros = [[robusto, maduro, foco em ferramentas complexas]],
            contras = [[muito atado ao brand atlassian]],
            licenca = "apache-2.0",
            empresa = "atlassian",
            estado = "ativo",
        },
        {
            nome = "carbon",
            tipo = "design_system",
            github = "https://github.com/carbon-design-system/carbon",
            docs = "https://carbondesignsystem.com/",
            stars = 8000,
            forks = 1800,
            ano = 2017,
            framework = [[react, angular, vue, svelte, web components]],
            base = [[especificacao + componentes (multi-framework)]],
            features = [[design system enterprise da ibm, data viz best-in-class,
                grid 2x, tokens, acessibilidade-first, modelo de contribuicao]],
            pros = [[enterprise/data-heavy, multi-framework, acessivel, data viz]],
            contras = [[menos consumer-oriented, docs densas, curva]],
            licenca = "apache-2.0",
            empresa = "ibm",
            estado = "ativo",
        },
        {
            nome = "chakra_ui",
            tipo = "biblioteca",
            github = "https://github.com/chakra-ui/chakra-ui",
            docs = "https://chakra-ui.com/",
            stars = 40000,
            forks = 3600,
            ano = 2019,
            framework = [[react (typescript)]],
            base = [[ark ui + panda css (v3)  / emotion css-in-js (v2)]],
            features = [[60+ componentes, style props, dark mode built-in, melhor
                acessibilidade (wai-aria, keyboard, screen reader), composavel]],
            pros = [[melhor acessibilidade da categoria, dx, theming, facil]],
            contras = [[css-in-js runtime (v2) impacta perf, menos componentes
                avancados que mui]],
            licenca = "mit",
            empresa = "chakra systems",
            estado = "ativo",
        },
        {
            nome = "cupertino_widgets",
            tipo = "biblioteca",
            github = "https://github.com/flutter/flutter",
            docs = "https://docs.flutter.dev/ui/widgets/cupertino",
            stars = 0,
            forks = 0,
            ano = 2017,
            framework = [[flutter (dart)]],
            base = [[implementa apple hig em flutter]],
            features = [[widgets estilo ios dentro do flutter, complementa material;
                desacoplamento material/cupertino em roadmap 2026]],
            pros = [[look ios em flutter, oficial]],
            contras = [[so flutter, nao 100% fiel ao nativo apple]],
            licenca = "bsd-3",
            empresa = "google",
            estado = "ativo",
        },
        {
            nome = "daisyui",
            tipo = "biblioteca",
            github = "https://github.com/saadeghi/daisyui",
            docs = "https://daisyui.com/",
            stars = 37000,
            forks = 1500,
            ano = 2020,
            framework = [[tailwind css plugin (framework-agnostic)]],
            base = [[tailwind css; sem js]],
            features = [[63 componentes (59 unicos), temas via css variables, sem
                js no browser, semantic class names, dark mode]],
            pros = [[framework-agnostic, temas faceis (css vars), leve, mais
                componentes que shadcn]],
            contras = [[so estilo (sem logica/acessibilidade propria), atado a
                tailwind]],
            licenca = "mit",
            empresa = "pouya saadeghi (oss)",
            estado = "ativo",
        },
        {
            nome = "element_plus",
            tipo = "biblioteca",
            github = "https://github.com/element-plus/element-plus",
            docs = "https://element-plus.org/",
            stars = 27000,
            forks = 4500,
            ano = 2020,
            framework = [[vue 3 (typescript)]],
            base = [[primitivos proprios]],
            features = [[sucessor do element ui, composition api, typescript forte,
                i18n built-in, limpo e confiavel]],
            pros = [[clean, ts forte, i18n, completo para vue 3]],
            contras = [[menos diferenciado visualmente, comunidade chinese-first]],
            licenca = "mit",
            empresa = "element / oss",
            estado = "ativo",
        },
        {
            nome = "fluent_ui",
            tipo = "design_system",
            github = "https://github.com/microsoft/fluentui",
            docs = "https://fluent2.microsoft.design/",
            stars = 19000,
            forks = 2700,
            ano = 2017,
            framework = [[react, react native, web components, native (multi)]],
            base = [[especificacao + componentes]],
            features = [[fluent 2, multiplataforma (web/win/ios/android/macos),
                tokens compartilhados + impl por plataforma, usado em teams/office/
                windows 11]],
            pros = [[cross-platform sofisticado, tokens compartilhados, backing
                microsoft]],
            contras = [[complexo, multiplos pacotes/versoes]],
            licenca = "mit",
            empresa = "microsoft",
            estado = "ativo",
        },
        {
            nome = "heroui",
            tipo = "biblioteca",
            github = "https://github.com/heroui-inc/heroui",
            docs = "https://www.heroui.com/",
            stars = 25000,
            forks = 1700,
            ano = 2021,
            framework = [[react (typescript)]],
            base = [[react aria + tailwind css]],
            features = [[ex-nextui (rebrand jan/2025), tailwind-native, react aria
                por baixo (acessivel), defaults bonitos, theming, dark mode]],
            pros = [[bonito out-of-the-box, tailwind-native, acessivel (react aria)]],
            contras = [[mais novo, ecossistema menor que mui]],
            licenca = "mit",
            empresa = "heroui inc",
            estado = "ativo",
        },
        {
            nome = "mantine",
            tipo = "biblioteca",
            github = "https://github.com/mantinedev/mantine",
            docs = "https://mantine.dev/",
            stars = 31200,
            forks = 2300,
            ano = 2021,
            framework = [[react (typescript)]],
            base = [[primitivos proprios + css modules]],
            features = [[100+ componentes, 100+ hooks,  css modules (mais rapido que
                css-in-js), dark mode, theming, completo]],
            pros = [[muitos componentes+hooks, css modules (perf), flexivel, dx]],
            contras = [[pode gerar css bloat de componentes nao usados]],
            licenca = "mit",
            empresa = "vitaly rtishchev (oss)",
            estado = "ativo",
        },
        {
            nome = "material_design_3",
            tipo = "design_system",
            github = "https://github.com/material-components",
            docs = "https://m3.material.io/",
            stars = 0,
            forks = 0,
            ano = 2021,
            framework = [[spec; impl em android (compose), web (mwc), flutter, etc]],
            base = [[especificacao]],
            features = [[m3, dynamic color (material you, espaco hct), tipografia,
                shape, motion fisica, window size classes/canonical layouts (adaptive),
                m3 expressive; evolucao do material design (2014)]],
            pros = [[adaptive design, dynamic color, vibrante, amplamente adotado
                (android)]],
            contras = [[google-centric (menos natural em ios), regras extensas]],
            licenca = "apache-2.0 (impl)",
            empresa = "google",
            estado = "ativo",
        },
        {
            nome = "material_ui",
            tipo = "biblioteca",
            github = "https://github.com/mui/material-ui",
            docs = "https://mui.com/",
            stars = 93000,
            forks = 32000,
            ano = 2014,
            framework = [[react (typescript)]],
            base = [[implementa material design; v7; joy ui e base ui como camadas]],
            features = [[70+ componentes, datagrid enterprise, theming maduro, sx
                prop, ~6.7m downloads/semana, joy ui/base ui para design custom]],
            pros = [[mais maduro/completo (datagrid/charts/date picker), suporte
                comercial, padrao da industria]],
            contras = [[customizacao sente "working around", theme tem curva,
                bundle maior]],
            licenca = "mit (core) / comercial (x)",
            empresa = "mui",
            estado = "ativo",
        },
        {
            nome = "naive_ui",
            tipo = "biblioteca",
            github = "https://github.com/tusen-ai/naive-ui",
            docs = "https://www.naiveui.com/",
            stars = 17000,
            forks = 1500,
            ano = 2021,
            framework = [[vue 3 (typescript)]],
            base = [[primitivos proprios]],
            features = [[90+ componentes tree-shakeable, ts first-class, theming
                customizavel (preview ao vivo), light/dark]],
            pros = [[tree-shakeable, ts, customizavel, performante]],
            contras = [[comunidade menor, mantido por tusimple]],
            licenca = "mit",
            empresa = "tusimple",
            estado = "ativo",
        },
        {
            nome = "park_ui",
            tipo = "biblioteca",
            github = "https://github.com/cschroeter/park-ui",
            docs = "https://park-ui.com/",
            stars = 2500,
            forks = 150,
            ano = 2023,
            framework = [[react, solid, vue (via ark ui)]],
            base = [[ark ui + panda css]],
            features = [[copy-paste (nao npm), multi-framework via ark ui, instala
                so o que precisa, customizavel/modular]],
            pros = [[controle total, multi-framework, modular, acessivel (ark)]],
            contras = [[manutencao manual de updates, mais novo]],
            licenca = "mit",
            empresa = "christian schroeter (oss)",
            estado = "ativo",
        },
        {
            nome = "polaris",
            tipo = "design_system",
            github = "https://github.com/Shopify/polaris",
            docs = "https://polaris.shopify.com/",
            stars = 6500,
            forks = 1200,
            ano = 2017,
            framework = [[react (implementacao)]],
            base = [[especificacao + componentes]],
            features = [[design system e-commerce da shopify, componentes commerce
                (product cards), wcag, foco em conversao, tokens/icons]],
            pros = [[otimizado para e-commerce/conversao, acessivel, integra shopify]],
            contras = [[muito especifico para commerce/shopify]],
            licenca = "custom (shopify)",
            empresa = "shopify",
            estado = "ativo",
        },
        {
            nome = "primereact",
            tipo = "biblioteca",
            github = "https://github.com/primefaces/primereact",
            docs = "https://primereact.org/",
            stars = 7500,
            forks = 1300,
            ano = 2019,
            framework = [[react (familia primevue/primeng tambem)]],
            base = [[primitivos proprios]],
            features = [[90+ componentes, 200+ icons, charts/datatable/treetable,
                temas pre-feitos + theme designer, integracao tailwind (primevue)]],
            pros = [[amplitude de componentes (data viz), temas, enterprise-ready]],
            contras = [[visual menos moderno por padrao, varios produtos separados]],
            licenca = "mit",
            empresa = "primetek",
            estado = "ativo",
        },
        {
            nome = "quasar",
            tipo = "biblioteca",
            github = "https://github.com/quasarframework/quasar",
            docs = "https://quasar.dev/",
            stars = 27000,
            forks = 3500,
            ano = 2015,
            framework = [[vue (framework completo, nao so ui)]],
            base = [[material design + primitivos proprios]],
            features = [[70+ componentes material, builds spa/ssr/pwa/mobile(capacitor)/
                desktop(electron) de um codebase, multiplos icon sets, anim/datas]],
            pros = [[cross-platform de um codebase, material, completo, performante]],
            contras = [[atado ao vue, framework opinativo]],
            licenca = "mit",
            empresa = "quasar (razvan stoenescu)",
            estado = "ativo",
        },
        {
            nome = "shadcn_ui",
            tipo = "biblioteca",
            github = "https://github.com/shadcn-ui/ui",
            docs = "https://ui.shadcn.com/",
            stars = 94000,
            forks = 6000,
            ano = 2023,
            framework = [[react (next.js); ports svelte/vue/solid/swift/blazor]],
            base = [[radix ui (ou base ui desde 2025) + tailwind css]],
            features = [[NAO e npm package: copy-paste de codigo no projeto (voce
                possui o codigo), 48+ componentes, cli, react 19/tailwind v4,
                code distribution platform]],
            pros = [[controle total/zero lock-in, tailwind-native, acessivel (radix),
                ideal para design system custom e workflows ai]],
            contras = [[voce mantem o codigo (updates manuais), poucos componentes
                avancados (sem datagrid), precisa tailwind]],
            licenca = "mit",
            empresa = "shadcn (vercel)",
            estado = "ativo",
        },
        {
            nome = "shadcn_svelte",
            tipo = "biblioteca",
            github = "https://github.com/huntabyte/shadcn-svelte",
            docs = "https://shadcn-svelte.com/",
            stars = 6000,
            forks = 600,
            ano = 2023,
            framework = [[svelte]],
            base = [[bits ui + tailwind css]],
            features = [[port comunitario (nao oficial, com bencao do shadcn) do
                shadcn/ui para svelte, copy-paste]],
            pros = [[shadcn para svelte, controle total, acessivel]],
            contras = [[nao oficial, comunidade menor, updates manuais]],
            licenca = "mit",
            empresa = "huntabyte (oss)",
            estado = "ativo",
        },
        {
            nome = "shadcn_vue",
            tipo = "biblioteca",
            github = "https://github.com/unovue/shadcn-vue",
            docs = "https://www.shadcn-vue.com/",
            stars = 6000,
            forks = 600,
            ano = 2023,
            framework = [[vue]],
            base = [[reka ui (ex radix vue) + tailwind css]],
            features = [[port comunitario do shadcn/ui para vue, copy-paste]],
            pros = [[shadcn para vue, controle total, acessivel]],
            contras = [[nao oficial, updates manuais]],
            licenca = "mit",
            empresa = "unovue (oss)",
            estado = "ativo",
        },
        {
            nome = "vuetify",
            tipo = "biblioteca",
            github = "https://github.com/vuetifyjs/vuetify",
            docs = "https://vuetifyjs.com/",
            stars = 40878,
            forks = 7000,
            ano = 2016,
            framework = [[vue (typescript)]],
            base = [[material design + primitivos proprios]],
            features = [[100+ componentes material, import modular (bundle pequeno),
                integra nuxt 3, theming poderoso, ~380k downloads/semana]],
            pros = [[material completo, maduro, comunidade forte, theming]],
            contras = [[atado a material design, alguns componentes v2 faltando em v3]],
            licenca = "mit",
            empresa = "vuetify (john leider)",
            estado = "ativo",
        },
    },
}
