return {
    descricao = [[
        camada 1 — linguagens de programacao usadas em desenvolvimento de ui.
        a linguagem sozinha nao desenha botao, e a fundacao. campos padronizados
        para mineracao de padroes entre camadas. dados 2025/2026.
    ]],
    itens = {
        {
            nome = "c",
            ano = 1972,
            criador = "dennis ritchie / bell labs",
            tipagem = [[estatica, fraca, manual de memoria]],
            paradigma = [[procedural, imperativa]],
            uso_ui = [[fundacao de toda ui embarcada e de motores graficos:
                lvgl, touchgfx, emwin, e o nucleo de skia/impeller, gtk]],
            frameworks_ui = [[lvgl, emwin, touchgfx (c/c++), gtk (c)]],
            embarcado = true,
            gc = false,
            pros = [[onipresente, footprint minimo, controla hardware diretamente,
                roda em qualquer mcu/bare metal]],
            contras = [[inseguranca de memoria, sem abstracoes modernas, verboso]],
            licenca = "n/a (padrao iso/ansi)",
            estado = "ativo",
        },
        {
            nome = "cpp",
            ano = 1985,
            criador = "bjarne stroustrup / bell labs",
            tipagem = [[estatica, forte-ish, manual+raii]],
            paradigma = [[multiparadigma: oo, generica, procedural]],
            uso_ui = [[motor de qt, qt for mcus, dear imgui, nuklear, wxwidgets,
                jucE, ue/godot ui, skia/impeller engine]],
            frameworks_ui = [[qt/qml, qt for mcus, dear imgui, nuklear, wxwidgets,
                touchgfx, emwin]],
            embarcado = true,
            gc = false,
            pros = [[performance nativa, controle total, ecossistema gigante de gui,
                escala de mcu a desktop]],
            contras = [[complexidade alta, compilacao lenta, inseguranca de memoria,
                curva de aprendizado]],
            licenca = "n/a (padrao iso)",
            estado = "ativo",
        },
        {
            nome = "csharp",
            ano = 2000,
            criador = "microsoft (anders hejlsberg)",
            tipagem = [[estatica, forte, gerenciada]],
            paradigma = [[multiparadigma: oo, funcional, generica]],
            uso_ui = [[ecossistema .net: maui, avalonia, uno platform, wpf, winforms,
                winui, xamarin (legado)]],
            frameworks_ui = [[avalonia, maui, uno platform, wpf, winui]],
            embarcado = false,
            gc = true,
            pros = [[produtividade alta, xaml, aot disponivel, ecossistema .net]],
            contras = [[gc (latencia), runtime pesado para embarcado, historico de
                churn de frameworks ui da microsoft]],
            licenca = "mit (dotnet runtime)",
            estado = "ativo",
        },
        {
            nome = "dart",
            ano = 2011,
            criador = "google (lars bak, kasper lund)",
            tipagem = [[estatica, forte, sound null safety]],
            paradigma = [[oo, reativa]],
            uso_ui = [[linguagem exclusiva do flutter; jit no dev (hot reload),
                aot no release]],
            frameworks_ui = [[flutter]],
            embarcado = false,
            gc = true,
            pros = [[hot reload, aot rapido, otimizada para ui declarativa,
                null safety]],
            contras = [[ecossistema quase so flutter/google, gc, fora de ui e nicho]],
            licenca = "bsd-3",
            estado = "ativo",
        },
        {
            nome = "go",
            ano = 2009,
            criador = "google (rob pike, ken thompson, robert griesemer)",
            tipagem = [[estatica, forte, gerenciada]],
            paradigma = [[procedural, concorrente (goroutines)]],
            uso_ui = [[ui e ponto fraco; bindings (fyne, gioui, walk); usada mais
                em backend/cli]],
            frameworks_ui = [[fyne, gio (gioui), wails (webview)]],
            embarcado = false,
            gc = true,
            pros = [[simples, compilacao rapida, binario unico, concorrencia]],
            contras = [[ecossistema ui imaturo, gc, sem generics ricos em ui]],
            licenca = "bsd-3",
            estado = "ativo",
        },
        {
            nome = "javascript",
            ano = 1995,
            criador = "brendan eich / netscape",
            tipagem = [[dinamica, fraca]],
            paradigma = [[multiparadigma: funcional, oo, prototipal, event-driven]],
            uso_ui = [[lingua franca da web e de webviews; react, vue, svelte,
                angular, solid, electron, react native, lynx]],
            frameworks_ui = [[react, vue, svelte, angular, solidjs, qwik, react
                native, electron, lynx, ionic]],
            embarcado = false,
            gc = true,
            pros = [[onipresente, maior ecossistema do mundo, roda em todo navegador,
                pool de devs gigante]],
            contras = [[tipagem fraca (mitigada por ts), performance variavel, gc]],
            licenca = "n/a (padrao ecmascript)",
            estado = "ativo",
        },
        {
            nome = "kotlin",
            ano = 2011,
            criador = "jetbrains",
            tipagem = [[estatica, forte, null safety]],
            paradigma = [[multiparadigma: oo, funcional]],
            uso_ui = [[linguagem oficial de android; jetpack compose e compose
                multiplatform (kmp para ios/desktop/web)]],
            frameworks_ui = [[jetpack compose, compose multiplatform]],
            embarcado = false,
            gc = true,
            pros = [[interop java, null safety, coroutines, compose multiplatform
                estavel em ios desde mai/2025]],
            contras = [[gc/jvm pesado, kotlin/native ainda evoluindo, fora de
                android e menos comum]],
            licenca = "apache-2.0",
            estado = "ativo",
        },
        {
            nome = "nim",
            ano = 2008,
            criador = "andreas rumpf",
            tipagem = [[estatica, forte, gc opcional]],
            paradigma = [[multiparadigma: imperativa, oo, funcional, metaprogramacao]],
            uso_ui = [[nicho; bindings gtk/imgui, figuro, fidget; compila para c]],
            frameworks_ui = [[fidget (figma-based), nimgl/imgui, gtk bindings]],
            embarcado = true,
            gc = false,
            pros = [[compila para c (portavel), gc opcional/arc, sintaxe python-like,
                metaprogramacao forte]],
            contras = [[comunidade pequena, ecossistema ui minimo, poucos jobs]],
            licenca = "mit",
            estado = "ativo",
        },
        {
            nome = "python",
            ano = 1991,
            criador = "guido van rossum",
            tipagem = [[dinamica, forte (duck typing)]],
            paradigma = [[multiparadigma: oo, funcional, imperativa]],
            uso_ui = [[kivy, tkinter, pyqt/pyside, dear pygui, flet (flutter),
                bindings de slint]],
            frameworks_ui = [[kivy, tkinter, pyqt, pyside, dear pygui, flet]],
            embarcado = false,
            gc = true,
            pros = [[produtividade altissima, ecossistema gigante, otima para
                prototipagem e ferramentas]],
            contras = [[lento (interpretado), gil, gc, distribuicao de apps dificil]],
            licenca = "psf license",
            estado = "ativo",
        },
        {
            nome = "rust",
            ano = 2010,
            criador = "graydon hoare / mozilla",
            tipagem = [[estatica, forte, ownership/borrow checker]],
            paradigma = [[multiparadigma: funcional, oo, sem gc, memory-safe]],
            uso_ui = [[explosao de frameworks ui: slint (embarcado), egui, iced,
                dioxus, leptos, yew, gpui (zed), makepad; e o tooling do lynx]],
            frameworks_ui = [[slint, egui, iced, dioxus, leptos, yew, gpui, makepad]],
            embarcado = true,
            gc = false,
            pros = [[seguranca de memoria sem gc, performance c-level, no_std para
                bare metal, roda de mcu a desktop/wasm]],
            contras = [[curva de aprendizado ingreme, compilacao lenta, ecossistema
                ui ainda fragmentado/imaturo]],
            licenca = "mit / apache-2.0",
            estado = "ativo",
        },
        {
            nome = "swift",
            ano = 2014,
            criador = "apple (chris lattner)",
            tipagem = [[estatica, forte, optionals]],
            paradigma = [[multiparadigma: oo, funcional, protocolar]],
            uso_ui = [[linguagem das plataformas apple: swiftui (declarativa, 2019)
                e uikit; tambem swift cross-platform (skiplate, swiftcrossui)]],
            frameworks_ui = [[swiftui, uikit, appkit]],
            embarcado = false,
            gc = false,
            pros = [[arc (sem gc tradicional), seguro, integracao nativa apple,
                swiftui declarativo]],
            contras = [[ecossistema preso ao mundo apple, cross-platform imaturo,
                swiftui closed-source]],
            licenca = "apache-2.0",
            estado = "ativo",
        },
        {
            nome = "typescript",
            ano = 2012,
            criador = "microsoft (anders hejlsberg)",
            tipagem = [[estatica (superset de js), forte, gradual]],
            paradigma = [[multiparadigma sobre javascript]],
            uso_ui = [[padrao de fato no frontend moderno e em rn/lynx; toda camada
                3 headless e majoritariamente ts]],
            frameworks_ui = [[react, vue, svelte, angular, solidjs, qwik, react
                native, lynx (reactlynx)]],
            embarcado = false,
            gc = true,
            pros = [[tipagem estatica sobre js, tooling excelente, reduz bugs,
                ecossistema npm inteiro]],
            contras = [[overhead de build, ainda compila para js (gc, runtime js)]],
            licenca = "apache-2.0",
            estado = "ativo",
        },
        {
            nome = "zig",
            ano = 2016,
            criador = "andrew kelley",
            tipagem = [[estatica, forte, manual de memoria (allocators)]],
            paradigma = [[procedural, imperativa, comptime metaprogramacao]],
            uso_ui = [[emergente; usada para tooling/engine, bindings, e como
                toolchain c/c++; ui propria ainda nascente]],
            frameworks_ui = [[capy (zig gui), bindings de raylib/imgui]],
            embarcado = true,
            gc = false,
            pros = [[sem gc, controle manual, comptime poderoso, otimo cross-compiler
                (substitui c), roda em bare metal]],
            contras = [[pre-1.0 (instavel), ecossistema ui quase inexistente,
                comunidade pequena]],
            licenca = "mit",
            estado = "ativo (pre-1.0)",
        },
    },
}
