//! Stage 3: ParserNode tree -> deterministic, formatted rust source against
//! the plev builder. Obeys the engine manual: theme tokens where resolved,
//! typography on the text run (one TextStyle per run), content-driven flow.

use crate::ir::{Arg, Param, ParserNode, Resolution, Tag, TextValue};

const IND: &str = "    ";

pub fn emit(res: &Resolution) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// generated by parser from {}; do not edit\n",
        res.source_label
    ));
    let uses_text = tree_any(&res.root, &|n| matches!(n.tag, Tag::Text(_)));
    let uses_justify = tree_any(&res.root, &|n| {
        n.props.iter().any(|p| {
            p.args
                .iter()
                .any(|a| matches!(a, Arg::Token(t) if t.starts_with("Justify::")))
        })
    });
    let uses_theme = tree_any(&res.root, &|n| {
        n.props.iter().any(|p| {
            p.args
                .iter()
                .any(|a| matches!(a, Arg::Token(t) if t.contains("theme.")))
        })
    });
    let mut builder_items: Vec<&str> = vec!["Element"];
    if uses_justify {
        builder_items.push("Justify");
    }
    builder_items.push("div");
    if uses_text {
        builder_items.push("text");
    }
    out.push_str(&format!(
        "use plev::builder::{{{}}};\n",
        builder_items.join(", ")
    ));
    if uses_theme {
        out.push_str("use plev::theme::Theme;\n");
    }
    out.push('\n');
    let params: Vec<String> = res
        .params
        .iter()
        .map(|p| match p {
            Param::Slot(n) => format!("{n}: Element"),
            Param::Text(n) => format!("{n}: &str"),
        })
        .collect();
    out.push_str(&format!(
        "pub fn {}({}) -> Element {{\n",
        res.fn_name,
        params.join(", ")
    ));
    if uses_theme {
        out.push_str(&format!("{IND}let theme = Theme::hoff();\n"));
    }
    out.push_str(IND);
    out.push_str(&render(&res.root, 1));
    out.push_str("\n}\n");
    out
}

fn tree_any(node: &ParserNode, pred: &dyn Fn(&ParserNode) -> bool) -> bool {
    pred(node) || node.children.iter().any(|c| tree_any(c, pred))
}

fn head(node: &ParserNode) -> String {
    match &node.tag {
        Tag::Div => "div()".into(),
        Tag::Text(TextValue::Param(p)) => format!("text({p})"),
        Tag::Text(TextValue::Literal(l)) => format!("text({l:?})"),
        Tag::Slot(name) => name.clone(),
    }
}

/// True when the node prints as a single expression with no chained calls.
fn is_inline(node: &ParserNode) -> bool {
    node.props.is_empty() && node.children.is_empty()
}

fn render(node: &ParserNode, depth: usize) -> String {
    let mut out = head(node);
    let pad = IND.repeat(depth + 1);
    for prop in &node.props {
        let args: Vec<String> = prop.args.iter().map(fmt_arg).collect();
        out.push_str(&format!("\n{pad}.{}({})", prop.name, args.join(", ")));
    }
    for child in &node.children {
        if is_inline(child) {
            out.push_str(&format!("\n{pad}.child({})", head(child)));
        } else {
            out.push_str(&format!(
                "\n{pad}.child(\n{pad}{IND}{}\n{pad})",
                render(child, depth + 2)
            ));
        }
    }
    out
}

fn fmt_arg(arg: &Arg) -> String {
    match arg {
        Arg::F32(v) => crate::css_map::fmt_f32(*v),
        Arg::Int(i) => i.to_string(),
        Arg::Pair([x, y]) => format!(
            "[{}, {}]",
            crate::css_map::fmt_f32(*x),
            crate::css_map::fmt_f32(*y)
        ),
        Arg::Token(t) => t.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::Prop;

    #[test]
    fn emits_deterministic_chain() {
        let res = Resolution {
            fn_name: "demo".into(),
            source_label: "demo.tsx".into(),
            root: ParserNode {
                tag: Tag::Div,
                props: vec![Prop::f32("w", 368.0), Prop::token("bg", "theme.colors.bg")],
                children: vec![ParserNode {
                    tag: Tag::Text(TextValue::Param("title".into())),
                    props: vec![Prop::f32("font_size", 20.0)],
                    children: vec![],
                }],
            },
            params: vec![Param::Text("title".into())],
            mapped: 3,
            dropped: vec![],
        };
        let a = emit(&res);
        let b = emit(&res);
        assert_eq!(a, b);
        assert!(a.contains("pub fn demo(title: &str) -> Element {"));
        assert!(a.contains("let theme = Theme::hoff();"));
        assert!(a.contains(".w(368.0)"));
        assert!(a.contains("text(title)"));
    }
}
