[package]
name = "basicIDE"
version = "0.1.0"
edition = "2024"
description = "Simple IDE test"

[[bin]]
name = "basicIDE"
path = "src/main.rs"

[dependencies]
plev = { path = "../..", package = "plev" }
wgpu = "28"
winit = { version = "0.30", features = ["rwh_06"] }
log = "0.4"
env_logger = "0.11"
pollster = "0.4"
web-time = "1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
