plugins {
    id 'com.android.application'
}

android {
    namespace 'com.plev.engine'
    compileSdk 35
    ndkVersion "27.2.12479018"

    defaultConfig {
        applicationId "com.plev.engine"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.games:games-activity:2.0.2'

    constraints {
        implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22') {
            because 'kotlin-stdlib-jdk7 merged into kotlin-stdlib'
        }
        implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22') {
            because 'kotlin-stdlib-jdk8 merged into kotlin-stdlib'
        }
    }
}
